Add missing config.h to build failure with strict checking
Without the config, clang complains about conflicting types

reader-tr03119.c:138:5: error: conflicting types for 'escape_pace_input_to_buf'
int escape_pace_input_to_buf(sc_context_t *ctx,
    ^
./reader-tr03119.h:87:5: note: previous declaration is here
int escape_pace_input_to_buf(sc_context_t *ctx,
    ^